import { useRouter } from 'next/router'
import Head from 'next/head';
import styles from '../../styles/Home.module.css'
import NavBar from '../components/NavBar';
import Loader from "../components/Loader";
import NoDataComponent from "../components/NoDataComponent";
import ImgList from "../components/ImgList";
import useSWR from 'swr';

const rowsPerPage = 10;


export default function Home(props) {
  const router = useRouter()
  const { page, search: searchQueryUri } = router.query;

  const {
    data,
  } = useSWR(
    `/api/${searchQueryUri ? "searchImage" : "fetchImage"}?page=${page || 1}&per_page=30${searchQueryUri ? "&"+searchQueryUri : ""}`
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Mohit&apos;s Unsplash Image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar
      />

      {
        !data
          ?
          <Loader />
          :
          !data || !Array.isArray(data) || (Array.isArray(data) && data.length === 0)
            ?
            <NoDataComponent />
            :
            <ImgList
              photosList={data}
              page={page}
              rowsPerPage={rowsPerPage}
            />
      }
    </div>
  )
}
/*
export async function getServerSideProps(context) {

  const { search, page } = context.query;

  let res;

  if (search) {
    res = await searchPhotos(search).catch(() => []);
  }
  else {
    res = await fetchPhotos(page || 1).catch(() => []);
  }

  if (!res) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      res
    },
  }
}
*/