import Head from 'next/head';
import styles from '../styles/Home.module.css'
import Image from 'next/image';

export default function Home({
  res
}) {
  console.log(res,`res`);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js!
        </h1>

      </main>
    </div>
  )
}

export async function getServerSideProps(context) {

  const res = await fetch(`${process.env.UNSPLASH_BASE_URL}/photos`, {
    headers : {
      "content-type" : "application/json",
      "accept" : "application/json",
      "Authorization" : `Bearer ${process.env.UNSPLASH_OAUTH_TOKEN}`
    }
  });

  const data = await res.json();


  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      res : data
    },
  }
}